p3ol/oak

packages/oak/lib/core/Row/index.styl

Before the generated classes were `oak-justify-flex-start` but css wanted a className like `oak-justify-start` to apply styles.
I simply added -flex- for css classname catching.
In addition, I added `space-around` and `space-between` that were not catched too. 
https://user-images.githubusercontent.com/10706836/126294055-133e6a85-8818-49a8-bed8-602e657217d6.mov

🐛fix(alignments): fix horizontal alignement - DASHV6-205

---

packages/oak-addon-basic-components/lib/core/Editor/BlockButton.js
packages/oak-addon-basic-components/lib/core/Editor/ColorButton.js
packages/oak-addon-basic-components/lib/core/Editor/index.js
packages/oak-addon-basic-components/lib/index.js
packages/oak-addon-basic-components/lib/languages/fr.js
packages/oak-addon-basic-components/package.json
packages/oak/package.json
yarn.lock

This fix editor base font size to avoid text increasing in editor to result in smaller text in component. 
In addition, I also added some translations for all the content editor tooltips.

🐛fix: oak text editor font size - DASHV6-226

---

packages/oak/lib/core/Option/index.js

It was missing a `preventDefault` on custom options so the clicks on those options were making a redirect.
https://user-images.githubusercontent.com/10706836/131682465-a4dbef46-9fd7-49ab-b437-59a4a9410702.mov

🐛fix(options): prevent redirects on custom options

---

packages/oak/lib/core/Option/index.js
packages/oak/lib/core/Row/index.options.js

removes preventDefault on general options button, because all the button were fucked up. Add it on drag & drop button only.

🐛fix(options): remove prevent default fuckery on options, and add it on drag & drop

---

packages/oak-addon-basic-components/lib/core/Image/index.settings.js
packages/oak/lib/core/Editable/Form.js

Because default value was `[]` for the image field value, the 
` { state.value ? (...) : ()` was truthy on opening when no image was provided to the field. So by default the field was displaying an empty image
In addition I replaced `f.[0]` into `f[0]` in Editable/Form.js because it failed with new babel version.

🐛fix: empty image on opening image field

---

packages/oak/lib/core/App/index.js

This adds overrides on the duplication. 
Also it became mandatory to enable multiple overrides for a components because `button` component has 2 overrides now (richtext and duplication), the `getOverrides` method was taking only the last override found. Now we rewrite overrides array to have one component per object and all its overrides inside.
w/ @emileNetter

✨ feat(overrides): add overrides on duplication and enable multiple overrides on a component

---

packages/oak-addon-richtext-field/lib/core/Editor/index.styl

this fixes `junipero` override on link popper inner padding, it also changes a `padding` into a `margin` to avoid placeholder positionning issue.

🐛fix(link): fix multiple link button selector issues

---

packages/oak/lib/core/Builder/index.js

This adds the ability to pass an `afterConstruct` method in overrides to add custom properties when appending a component.

✨ feat(overrides): allow overriding of construct on append

---

packages/oak/lib/core/App/index.js

Issue emerged after adding `options` in dependency list causing multiple renders. A previously added group would be added a second time, leading to strange behaviors.

🐛 fix(oak): prevent component being added to wrong group

---

packages/oak-addon-basic-components/package.json
packages/oak-addon-richtext-field-prosemirror/package.json
packages/oak-addon-richtext-field/package.json

This force packages to use peer dependency for oak package and not direct dependency to avoid mismatching oak version between packages.

🐛fix(oak): remove oak from dependencies of all packages to avoid oak version mismatches

---

packages/oak-addon-richtext-field-prosemirror/lib/core/Editor/schema.js

Simply moved down underline component to make it applied **after** color one. Which implies color to be applied to underline line. 
Before
After

🐛 fix(prosemirror): change order to apply color on underline line - ACCESS-217

---

packages/oak-react/lib/index.js
packages/oak-react/lib/index.stories.js
packages/oak/lib/core/App/index.js

The undo redo problem was due to init which was made each time `options` object changed. As this object is destructured in `oak-react` wrapper (especially with `rest` props), it was quite impossible to just memo props to avoid unecessary rerender.
I solved the problem by disabling the content replaacement when `options.content` props change after the first render. 
If the user want to force a new content to be set after the first oak render, he as to use the `setContent` method passed by the Ref (and may be by the future context wrapper). 
For me it's more logical as most of the time the new content come from oak, it hasn't to be resent to Oak after parent app as effectively changed.

🐛fix: disable the possibility to update content with content props after first render

---

packages/oak-react/lib/index.js
packages/oak/lib/index.js

Use `render` function inside a useEffect instead of App exported component `Builder` to prevent our Builder from being rerendered each times parent component is rerendered.

🐛fix: react rerender problems

---

packages/oak/lib/core/App/index.js
packages/oak/lib/index.js

There's a world where React prevents infinite renders caused by a `useEffect` with `props` as dependencies, and there's a world where things like Preact don't.
This fixes potential infinite renders due to a bad pattern to begin with, even if React is more permissive and just ignored it all this time.

🐛 fix(lib): prevent infinite renders due to options being real props

---

packages/oak-react/lib/index.js
packages/oak-react/lib/index.stories.js
packages/oak/lib/core/App/index.js
packages/oak/lib/index.js

Currently, we use `render` method (which create oak `App` component and set `options` in it) once on a useEffect with an empty dependancy array. The problem with this, is that if options change, Oak will never be aware of it, because the render is responsible of passing options from oak-react to oak.
We could choosing rerendering oak with new options each times it changes but undo/redo was affected as the memory was reset.
I so chose to add a `setOptions` method on oak, and trigger it every times options are updated on react. It allows us to keep one rendering (usefull to keep undo redo working) BUT having updated options

🐛fix(oak-react): add a setOptions method to update options

---

packages/oak-addon-richtext-field-prosemirror/lib/core/Editor/index.js
packages/oak-addon-richtext-field-prosemirror/lib/core/Editor/index.test.js
packages/oak-addon-richtext-field-prosemirror/lib/core/Editor/schema.js
packages/oak-addon-richtext-field-prosemirror/lib/hooks.test.js
packages/oak-addon-richtext-field-prosemirror/lib/index.stories.js
packages/oak/lib/index.stories.js

Because we used to parse color using the `span` tag type and not the color attribute inside of it, if we had many styles on a single tag, (for example `<span style="color:#ffffff: font-size: 10px">content</span>`) the color was not parsed by prosemirror and the text was considered as default (black in our case). This led us to problems when parsing complex HTML. 
In addition of this fix, I added some unit tests on our `useProsemirror` hook and on the Editor.

🐛fix(prosemirror): improve prosemirror color parsing

---

packages/core/lib/Overrides/index.js
packages/react/lib/Editable/Field.js

Don't really understand why this has been deleted on the #1147 ?
Reusing this field overrides make ckeditor working again, and seems to be useful as the builder stores fields overrides in the fields 
https://github.com/p3ol/oak/blob/0947dcbc8522311f7893c437418f71ea55296244/packages/core/lib/Builder/index.js#L71-L74
What do you think guys ? @antoinechassagne @dackmin

🐛fix: reuse getField when getting overrides

---

packages/core/lib/types.d.ts
packages/react/lib/Editable/Field.js
packages/react/lib/Editable/Form.js

This addition allows to access the builder in the `condition` callback. This offers new possibilities such as accessing the entire content and basing the condition on it.

✨ feat(react): add builder to condition callback

---

packages/core/lib/Builder/index.js
packages/core/lib/types.d.ts
packages/react/lib/DisplayableSettings/index.js
packages/react/lib/Editable/Form.js
packages/react/lib/index.stories.js

We can now override settings priority : 
```js
const builder = new Builder({
addons: [{
overrides: [{
type: 'component',
targets: ['button'],
fields: [{
key: 'foo',
priority: 2,
}, {
key: 'bar',
priority: 1,
}],
}],
}, {
id: 'fooOverride',
type: 'setting',
targets: ['button'],
key: 'settings.foo',
priority: 1,
}],
});
```
In this exemple, the order will be : `foo` then `bar`. 
This PR also changes the order in which displayable settings are displayed to have the same order as in `<Form />`.

✨ feat(react): add priority override for settings

---

packages/react/lib/components/Col/index.tsx
packages/react/lib/components/Row/index.tsx

Background preview already exists on row, but is a nice to have on col too.
It will disappear when the parent row has more than 6 cols to avoid cluttering the col options.

✨ feat(react): add background preview to col component

---

packages/core/lib/classes.ts
packages/core/lib/types.ts
packages/react/lib/DisplayableSettings/Property.tsx
packages/react/lib/Editable/Field.tsx
packages/react/lib/Editable/Form.tsx
packages/react/lib/Editable/Setting.tsx
packages/react/lib/Editable/Tab.tsx
packages/react/lib/index.stories.tsx
packages/react/lib/utils.ts

This PR:
- Fixes settings overrides -> no more disappearing properties
- Fixes displayable properties not being re-rendered when an editable updates an element content
- Introduces some types `TODO`s because I'm tired and want to play elden ring

🐛 fix: correctly handle settings overrides

---

packages/core/lib/addons.ts
packages/react/lib/DisplayableSettings/index.tsx
packages/react/lib/Editable/Tab.tsx
packages/react/lib/index.stories.tsx

Fields only declared inside a component override are currently ignored and not rendered.
As settings fields declared inside a component override are already considered in typings as `ComponentSettingsFieldObject`s, it seemed natural to handle them accordingly and append these fields inside the editable form.

🐛 fix: correctly handle custom fields from component overrides

---

packages/react/lib/Builder/index.test.tsx.snap
packages/react/lib/DynamicComponent/index.tsx
packages/react/lib/Element/index.tsx
packages/react/lib/addons.tsx
packages/react/lib/components/Clickable/index.tsx
packages/react/lib/components/Foldable/index.tsx
packages/react/lib/components/Row/index.tsx
packages/react/lib/contexts.ts
packages/react/lib/hooks.ts
packages/react/lib/options.tsx

This allow oak user to collapse complex block to have a better comprehension oh his oak content
use case: 
https://github.com/user-attachments/assets/8f0f14d1-d039-459f-b0b1-7ed0c9046f00

✨feat(react): add a collapse option for inner content blocks on builder

---

packages/core/lib/Builder/index.test.ts.snap
packages/core/lib/Components/index.test.ts.snap
packages/core/lib/Overrides/index.test.ts.snap
packages/core/lib/classes.ts
packages/core/lib/types.ts
packages/react/lib/Catalogue/index.tsx
packages/react/lib/Container/index.tsx
packages/react/lib/Element/index.tsx
packages/react/lib/components/Col/index.tsx
packages/react/lib/components/Row/index.tsx
packages/react/lib/index.stories.tsx
packages/theme/lib/Element.sass
packages/theme/lib/Option.sass

`usable` -> not available in catalogue but still displayed inside the builder if it exists to avoid resolving to `Unknown`
`droppable` -> cannot drop children inside containers, but as it's too complicated to do it recursively, can still drop before/after
Other options are pretty self explanatory.

✨ feat: allow components (& overrides) to not be usable, editable, copyable, duplicable, draggable & droppable

---

packages/react/lib/Container/index.tsx
packages/react/lib/Element/index.tsx
packages/react/lib/components/Clickable/index.tsx
packages/react/lib/components/Col/index.tsx
packages/react/lib/components/Foldable/index.tsx
packages/react/lib/components/Row/index.tsx

Drag & drop has been utterly fucked since 3.9.0 because of various false flags:
- `Element` (which is the basis of all elements in the builder, even container-able components like row) was not preventing drops when it was disabled, because the check has been moved to the parent component: in theory it works, except for pre-disabled components (e.g anything with a container—row, clickable, foldable, ...) that need their underlying element to be non-droppable
- `Element`'s droppable not being disabled correctly, dragging/dropping an element inside a container-able would trigger `onDrop` on both the moved element AND the parent, resulting on the element being removed from its parent and moved above
I brought back the `disabled` prop on `Element`'s droppable, and moved the check for …

🐛 fix: correctly handle drag & drop 

---

packages/addon-ckeditor5-react/lib/Field/index.tsx
packages/addon-ckeditor5-react/lib/addons.ts

CKEditor heavily relies on `window` without ever checking for it to not be undefined (and doesn't plan to change this anytime soon 😒 https://github.com/ckeditor/ckeditor5-react/issues/36), so this loads the classic editor in a `useEffect` to prevent it from being imported during server-side rendering.

🐛 fix(ckeditor5-react): prevent ckeditor from loading on server side

---

packages/react/lib/Builder/index.tsx
packages/react/lib/components/Button/index.tsx
packages/react/lib/components/Text/index.tsx
packages/react/lib/components/Title/index.tsx
packages/react/lib/contexts.ts
packages/react/lib/hooks.ts
packages/react/lib/utils.ts

`DOMParser` is a client-side DOM level 1 class that doesn't exist in a server side environment. This creates hydratation errors as the sanitized html would be `''` on the server, but the right value on the client.
To prevent this, I added the ability to pass spec-compatible DOMParser & XMLSerializer polyfills to the builder (for example `@xmldom/xmldom` can be used on both client & server), and adapted the code a bit to not use `querySelector` that was not implemented in most of the xml-compatible parsers.

🐛 fix(react): allow to use polyfills to parse html

---

packages/react/lib/Editable/Field.tsx
packages/react/lib/Editable/Tab.tsx
packages/react/lib/index.stories.tsx
packages/react/lib/utils.ts

This PR fixes 3 issues with overrides : 
- props from setting overrides were not applied
- field override took the precedence over setting override (now setting override > field override)
- when overriding a component's field that uses multiple keys, the corresponding field was not correctly retrieved so it was duplicated

🐛 fix(react): fix overrides

---

packages/core/lib/types.ts
packages/react/lib/Editable/Setting.tsx
packages/react/lib/index.stories.tsx

On `Editable` display, the `Setting` component uses overrides `condition` function to know whether it ghas to display component, or not. And Call `Field` component if its truthy to display Field component, that reuse some overrides to know which field as to be displayed if a field has to. But, as the `Setting` was not using `ComponentOverrides` and only `SettingOverrides` it led that if a `ComponentOverride` wants to hide a field, it can not hide the title of it. 
This fix this behavior

🐛fix: component override on setting
